import { useEffect, useRef } from "react"
import { claimSharedOutbox, releaseSharedOutbox, isSharedOutboxHeld } from "../hooks/useMessages"
import { isSessionActive } from "../utils"
import { formatBytesMemory } from "../utils/format"
import { modelKey } from "../utils/model-utils"
import type { LanguageCode } from "../i18n"
import { useBaseChatProps } from "../features/chat/hooks/useBaseChatProps"
import { useConnectionRuntime } from "./runtime/useConnectionRuntime"
import { useChatRuntime, useChatActionsRuntime } from "./runtime/useChatRuntime"
import { useWorkspaceRuntime } from "./runtime/useWorkspaceRuntime"

export type UseAppControllerParams = {
  language: LanguageCode
  setLanguage: (lang: LanguageCode) => void
}

/**
 * Compositor de la app: arma los slices de los tres runtimes de dominio
 * (`connection`, `chat`, `workspace`) y devuelve el MISMO objeto plano que
 * consumen los llamadores (App y subcomponentes). La forma de `app` no cambia
 * en esta onda; B4 consumirá los slices directamente.
 */
export function useAppController({ language, setLanguage }: UseAppControllerParams) {
  const conn = useConnectionRuntime({ language, setLanguage })
  const chat = useChatRuntime({ conn })
  const ws = useWorkspaceRuntime({ conn, chat })
  const act = useChatActionsRuntime({ conn, chat, ws })

  const {
    t,
    isDesktop,
    theme,
    setTheme,
    handleLanguageChange,
    handleToggleLightMode,
    config,
    draftConfig,
    setDraftConfig,
    handleTest,
    testingConnection,
    canTestDraft,
    testAlreadyPassedForDraft,
    connectedVersion,
    settingsNotice,
    dataMode,
    changeDataMode,
    connectionState,
    modelOptions,
    modelLoadError,
    modelQuery,
    setModelQuery,
    selectedModelKey,
    changeModel,
    changeAgent,
    allPrimaryAgents,
    disabledAgents,
    toggleAgentEnabled,
    agentOptions,
    activeAgentID,
    blockedModels,
    filteredVariantGroups,
    flags,
    toggleFlag,
    setFlag,
    providerList,
    connectingProvider,
    providerError,
    connectProvider,
    disconnectProvider,
    addCustomProvider,
    removeCredential,
    activateCredential,
    loadModels,
    serverProfiles,
    addProfile,
    updateProfile,
    removeProfile,
    applyServerProfile,
    activeServerProfileID,
    setActiveServerProfileID,
    saveConfig,
    queueAction,
    handleOpenGitHub,
    sidebarPrefs,
  } = conn

  const {
    composer,
    handleComposerChange,
    isSending,
    awaitingAssistantReply,
    runtimeError,
    setRuntimeError,
    outbox,
    removeOutbox,
    activeDetailSheet,
    setActiveDetailSheet,
    projectDashboard,
    totalDiffAdditions,
    totalDiffDeletions,
    dashboardError,
    diffFiles,
    commands,
    setCommands,
    commandFilter,
    setCommandFilter,
    helpPage,
    setHelpPage,
    query,
    setQuery,
    chatSettings,
    setChatSetting,
    resetChatSettings,
    promptSnippets,
    addSnippet,
    removeSnippet,
    vs,
  } = chat

  const {
    view,
    goBack,
    navStackRef,
    handleNavigate,
    setShowThemePicker,
    setShowThemeCreator,
    setShowFavoritesManager,
    setShowArchivedView,
    setShowShortcuts,
    setShowOpenCodeHub,
    setShowMCPBrowser,
    setShowConnectSheet,
    setShowPluginsModal,
    showShortcuts,
    showThemePicker,
    showThemeCreator,
    showConnectSheet,
    showMCPBrowser,
    showArchivedView,
    showFavoritesManager,
    showOpenCodeHub,
    showRemoteDesktop,
    setShowRemoteDesktop,
    showPluginsModal,
    fileEditorPath,
    setFileEditorPath,
    desktopCfg,
    desktopDiffData,
    sessions,
    selectedID,
    refreshingSessions,
    creatingSession,
    selectedSession,
    sessionToDelete,
    renamingSessionID,
    renameValue,
    setRenameValue,
    refreshSessions,
    refreshSessionsWithIndicator,
    renameSession,
    startRename,
    cancelRename,
    setSessionToDelete,
    favorites,
    toggleFavorite,
    handleDeleteSession,
    setDesktopLayout,
    desktopLayout,
    tabStacks,
    activePanel,
    setActivePanel,
    activity,
    setActivity,
    sidebarCollapsed,
    setSidebarCollapsed,
    rightSidebarCollapsed,
    setRightSidebarCollapsed,
    desktopDiffOpen,
    setDesktopDiffOpen,
    setDesktopDiffWidth,
    switchTab,
    removeTab,
    moveTab,
    transferTab,
    addTerminalToPanel,
    detachTab,
    closeOthers,
    closeRight,
    closeLeft,
    closeAll,
    closePanel,
    handleDockSession,
    handleShutdownHost,
    handleRestartHost,
    handleDeleteMany,
    handleArchiveMany,
    openSessionInDir,
    openBrowserAsTab,
    handleOpenBrowser,
    openPluginAsTab,
    openExternalProject,
    handleOpenNewSession,
    handleCreateSession,
    ensureStudioSession,
    fb,
    handleOpenExplorer,
    shellExecute,
    handleOpenSession,
    filteredProjects,
    filteredProjectSessions,
    selectedProjectDir,
    setSelectedProjectDir,
    projectName,
    projectPath,
    vcsBranch,
    activeSessions,
    recentSessions,
    busySessions,
    dismissRecent,
    shellRef,
    shellGridStyle,
    startSidebarResize,
    startRightSidebarResize,
    maximizedPanel,
    setMaximizedPanel,
    handleOpenKanban,
    handleOpenLearning,
    currentActiveSession,
    activeSessionDir,
    handleSessionDragStart,
    openInPanel,
    handleSwapPanels,
    handleOpenFile,
    showNewSessionPicker,
    pickerDir,
    pickerItems,
    pickerLoading,
    pickerError,
    browseNewSessionDirectory,
    setPickerError,
    setShowNewSessionPicker,
  } = ws

  const {
    activeModelOption,
    selectedVariant,
    memInfo,
    settleSession,
    handleSend,
    handleBrowserVisualPick,
    handleToggleInspectTool,
  } = act

  const isSessionRunning = Boolean(selectedSession && isSessionActive(selectedSession))
  // stopping/chatStopping NO entran acá: el guard anti-deltas vive en
  // stopGenerationRef (fondo) y la burbuja debe caer al confirmar el stop.
  const isWorking = awaitingAssistantReply || isSessionRunning

  const baseChatProps = useBaseChatProps({ conn, chat, ws, act, isWorking })

  // Auto-flush de la cola visible (móvil/detalle): al quedar libre, sale el
  // pendiente más antiguo de la sesión seleccionada. Claim compartido: la
  // cola es por sesión entre todas las instancias (un panel desktop puede
  // estar mostrando la misma sesión).
  //
  // Reglas anti-bucle:
  // - no correr con la sesión ocupada (si no `handleSend` RE-ENCOLA en vez de
  //   enviar y cada render duplica el pendiente — el bucle infinito reportado);
  // - `force=true`: el item ya está en la cola, no debe volver a encolarse;
  // - cooldown de 4s para fallos repetidos (no reintentar en cada render);
  // - hold tras Stop explícito (ver `holdSharedOutbox`).
  const outboxFlushingRef = useRef(false)
  const outboxLastTryRef = useRef(0)
  useEffect(() => {
    if (!selectedSession || isSending || awaitingAssistantReply) return
    if (isSessionActive(selectedSession)) return
    if (isSharedOutboxHeld(selectedSession.id)) return
    if (outboxFlushingRef.current) return
    if (Date.now() - outboxLastTryRef.current < 4_000) return
    const next = outbox.find((o) => o.sessionID === selectedSession.id)
    if (!next || !claimSharedOutbox(next.id)) return
    outboxLastTryRef.current = Date.now()
    outboxFlushingRef.current = true
    void (handleSend(next.images, undefined, next.text, true) as Promise<unknown>).then((res) => {
      if (res !== false) removeOutbox(next.id)
      else releaseSharedOutbox(next.id)
    }).catch(() => releaseSharedOutbox(next.id)).finally(() => {
      outboxFlushingRef.current = false
    })
  })

  return {
    t,
    isDesktop,
    view,
    theme,
    setTheme,
    language,
    handleLanguageChange,
    handleToggleLightMode,
    config,
    draftConfig,
    setDraftConfig,
    handleTest,
    testingConnection,
    canTestDraft,
    testAlreadyPassedForDraft,
    connectedVersion,
    settingsNotice,
    dataMode,
    changeDataMode,
    modelOptions,
    selectedModelKey,
    changeModel,
    modelKey,
    selectedVariant,
    allPrimaryAgents,
    disabledAgents,
    toggleAgentEnabled,
    activeModelOption,
    blockedModels,
    setShowThemePicker,
    setShowThemeCreator,
    flags,
    toggleFlag,
    setFlag,
    providerList,
    connectingProvider,
    providerError,
    connectProvider,
    disconnectProvider,
    addCustomProvider,
    removeCredential,
    activateCredential,
    loadModels,
    serverProfiles,
    addProfile,
    updateProfile,
    removeProfile,
    applyServerProfile,
    activeServerProfileID,
    setActiveServerProfileID,
    saveConfig,
    chatSettings,
    setChatSetting,
    resetChatSettings,
    promptSnippets,
    addSnippet,
    removeSnippet,
    handleShutdownHost,
    handleRestartHost,
    handleOpenGitHub,
    setShowFavoritesManager,
    setShowArchivedView,
    setShowShortcuts,
    setShowOpenCodeHub,
    navStackRef,
    goBack,
    helpPage,
    setHelpPage,
    commands,
    setCommands,
    commandFilter,
    setCommandFilter,
    shellRef,
    sidebarPrefs,
    shellGridStyle,
    activity,
    setActivity,
    sidebarCollapsed,
    setSidebarCollapsed,
    tabStacks,
    desktopLayout,
    openBrowserAsTab,
    handleOpenBrowser,
    handleOpenKanban,
    rightSidebarCollapsed,
    setRightSidebarCollapsed,
    setShowPluginsModal,
    showPluginsModal,
    openPluginAsTab,
    openExternalProject,
    memInfo,
    formatBytes: formatBytesMemory,
    handleOpenLearning,
    handleNavigate,
    currentActiveSession,
    activeSessionDir,
    selectedSession,
    fb,
    startSidebarResize,
    startRightSidebarResize,
    maximizedPanel,
    setMaximizedPanel,
    sessions,
    busySessions,
    connectionState,
    baseChatProps,
    composer,
    handleComposerChange,
    fileEditorPath,
    setFileEditorPath,
    vs,
    setDesktopLayout,
    setActivePanel,
    activePanel,
    removeTab,
    moveTab,
    transferTab,
    addTerminalToPanel,
    detachTab,
    closeOthers,
    closeRight,
    closeLeft,
    closeAll,
    closePanel,
    handleDockSession,
    settleSession,
    refreshSessions,
    queueAction,
    shellExecute,
    changeAgent,
    openInPanel,
    handleSwapPanels,
    handleOpenFile,
    setShowConnectSheet,
    openSessionInDir,
    handleToggleInspectTool,
    handleBrowserVisualPick,
    switchTab,
    desktopDiffOpen,
    setDesktopDiffOpen,
    desktopDiffData,
    diffFiles,
    setDesktopDiffWidth,
    filteredProjects,
    filteredProjectSessions,
    selectedProjectDir,
    setSelectedProjectDir,
    selectedID,
    refreshingSessions,
    creatingSession,
    renamingSessionID,
    renameValue,
    setRenameValue,
    query,
    setQuery,
    activeSessions,
    recentSessions,
    favorites,
    toggleFavorite,
    refreshSessionsWithIndicator,
    handleOpenNewSession,
    handleOpenSession,
    startRename,
    renameSession,
    cancelRename,
    setSessionToDelete,
    sessionToDelete,
    deleteSession: handleDeleteSession,
    dismissRecent,
    handleCreateSession,
    ensureStudioSession,
    handleOpenExplorer,
    handleSessionDragStart,
    handleDeleteMany,
    handleArchiveMany,
    showNewSessionPicker,
    pickerDir,
    pickerItems,
    pickerLoading,
    pickerError,
    browseNewSessionDirectory,
    setPickerError,
    setShowNewSessionPicker,
    activeDetailSheet,
    setActiveDetailSheet,
    modelLoadError,
    filteredVariantGroups,
    modelQuery,
    setModelQuery,
    projectName,
    projectPath,
    vcsBranch,
    projectDashboard,
    totalDiffAdditions,
    totalDiffDeletions,
    dashboardError,
    showThemePicker,
    showThemeCreator,
    showConnectSheet,
    showMCPBrowser,
    setShowMCPBrowser,
    showArchivedView,
    desktopCfg,
    showShortcuts,
    showFavoritesManager,
    showOpenCodeHub,
    agentOptions,
    activeAgentID,
    runtimeError,
    setRuntimeError,
    showRemoteDesktop,
    setShowRemoteDesktop,
  }
}
