import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import { cssBundle } from './css-bundle.mjs'

const sessionList = readFileSync(new URL('./components/SessionList.tsx', import.meta.url), 'utf8')
const sessionToolbar = readFileSync(new URL('./components/SessionToolbar.tsx', import.meta.url), 'utf8')
const msgList = readFileSync(new URL('./components/MessageList.tsx', import.meta.url), 'utf8')
const composer = readFileSync(new URL('./components/Composer.tsx', import.meta.url), 'utf8')
const sessionCard = readFileSync(new URL('./components/SessionCard.tsx', import.meta.url), 'utf8')
const app = readFileSync(new URL('./App.tsx', import.meta.url), 'utf8')
const controller = readFileSync(new URL('./app/useAppController.ts', import.meta.url), 'utf8')
const baseChatPropsSource = readFileSync(new URL('./features/chat/hooks/useBaseChatProps.ts', import.meta.url), 'utf8')
const hostActions = readFileSync(new URL('./features/host-actions/hooks/useHostActions.ts', import.meta.url), 'utf8')
const lifecycle = readFileSync(new URL('./features/app-lifecycle/hooks/useAppLifecycle.ts', import.meta.url), 'utf8')
const api = readFileSync(new URL('./api.ts', import.meta.url), 'utf8')
const useMessages = readFileSync(new URL('./hooks/useMessages.ts', import.meta.url), 'utf8')
const useAI = readFileSync(new URL('./hooks/useAI.ts', import.meta.url), 'utf8')
const useSessions = readFileSync(new URL('./hooks/useSessions.ts', import.meta.url), 'utf8')
const useConfig = readFileSync(new URL('./hooks/useConfig.ts', import.meta.url), 'utf8')
const icons = readFileSync(new URL('./Icons.tsx', import.meta.url), 'utf8')
const styles = cssBundle()

const refreshButton = sessionToolbar.match(/<button onClick=\{handleRefresh\}[\s\S]*?<LoadingIcon[\s\S]*?<\/button>/)
assert.ok(refreshButton, 'sessions refresh button should call refreshSessionsWithIndicator')
assert.ok(refreshButton[0].includes('RefreshIcon'), 'idle sessions refresh button should render a non-spinning RefreshIcon')
assert.ok(refreshButton[0].includes('refreshing ? <LoadingIcon'), 'refresh button should spin only during an active manual refresh')
assert.ok(sessionToolbar.includes('setRefreshFeedback(ok ? "ok" : "fail")'), 'refresh button should show ok/fail feedback based on the refresh result')
assert.ok(sessionToolbar.includes('onRefresh: () => Promise<boolean>'), 'refresh should resolve whether it succeeded')

assert.ok(useMessages.includes('messageScrollSignature'), 'conversation auto-scroll should react to message content changes, not only message count')
assert.ok(msgList.includes('scrollToBottom("auto")'), 'auto-scroll should re-anchor the conversation at the bottom on new messages')
assert.ok(composer.includes('behavior: "smooth"'), 'focusing the composer should scroll to the bottom')
assert.ok(msgList.includes('messagesEndRef'), 'auto-scroll should target a bottom sentinel marker')
assert.ok(msgList.includes('scrollTo({ top: container.scrollHeight'), 'auto-scroll should set the messages container scrollTop to its max scrollHeight')
assert.ok(msgList.includes('scrollIntoView'), 'auto-scroll should scroll the sentinel into view as a fallback')
assert.ok(composer.includes('composerRef'), 'auto-scroll should know the sticky composer height so the latest message is not hidden behind input controls')
assert.ok(composer.includes('scrollTo') || msgList.includes('scrollTo'), 'auto-scroll should set container scrollTop')
assert.ok(/\.messages[\s\S]*?padding-bottom:\s*(var\(--space-2\)|env\(safe-area-inset-bottom\))/.test(styles), 'messages pane should reserve bottom space')
assert.ok(/\.messages-end[\s\S]*?scroll-margin-bottom:\s*var\(--space-2\)/.test(styles), 'bottom sentinel should keep the latest output above the sticky composer')
assert.ok((composer + msgList).includes('requestAnimationFrame'), 'auto-scroll should use requestAnimationFrame')
assert.ok(sessionCard.includes('session-card'), 'session card should have card class')
assert.ok(app.includes('typing-bubble') || msgList.includes('typing-bubble'), 'detail view should render a temporary typing bubble while waiting for OpenCode output')
assert.ok(msgList.includes('GridSpinner'), 'typing bubble should show the grid spinner')
assert.ok(useMessages.includes('awaitingAssistantReply'), 'typing bubble should stay visible after the send request returns and until a new assistant message arrives')
assert.ok(useMessages.includes('assistantResponseSignature'), 'typing bubble should be replaced by the next assistant response')
assert.ok(useMessages.includes('optimisticUserMessages'), 'sent user messages should render immediately before the network round trip returns')
assert.ok(useMessages.includes('createOptimisticUserMessage') || useMessages.includes('optimisticMessage'), 'send flow should create an optimistic user message envelope')
assert.ok((app + controller).includes('isWorking = awaitingAssistantReply || isSessionRunning'), 'working state should track assistant reply and session status for typing bubble')
assert.ok(composer.includes('isWorking') && composer.includes('onAbort'), 'composer should show abort button when working')
assert.ok(composer.includes('handleSendWithImages') && !composer.includes('onClick={isWorking ? onAbort : onSend}'), 'send button should always be available for multiple prompts')
assert.ok(useMessages.includes('completionShouldPlayRef.current = true'), 'completion sound should be armed when a real assistant reply is expected')
const completionAudio = readFileSync(new URL('./hooks/useCompletionAudio.ts', import.meta.url), 'utf8')
assert.ok(completionAudio.includes('wasAwaitingRef.current && !awaitingAssistantReply'), 'completion sound should play only when assistant waiting ends, not when the user bubble renders')
assert.ok(completionAudio.includes('completionShouldPlayRef.current'), 'completion sound armed flag should be checked')
assert.ok(useMessages.includes('loadSelectedRequestRef'), 'session message refreshes should ignore stale overlapping polling responses')
assert.ok(useMessages.includes('if (requestID !== loadSelectedRequestRef.current) return'), 'older loadSelected requests must not overwrite newer assistant output')
assert.ok(useMessages.includes('setMessages((prev)'), 'message refresh should merge server data with existing, dedup by id')
assert.ok(composer.includes('SendIcon'), 'composer send button should use the clear paper-plane SendIcon')
assert.ok(composer.includes('StopCircleIcon'), 'composer waiting button should use a clear stop-task icon')
assert.match(icons, /export const StopCircleIcon/, 'StopCircleIcon should exist in the shared SVG icon set')
assert.ok(api.includes('loadDiff(config: ServerConfig, sessionID: string, directory?: string)'), 'detail view should load /session/:id/diff for changed-file details')
const sheetFile = readFileSync(new URL('./components/BottomSheet.tsx', import.meta.url), 'utf8')
assert.ok(sheetFile.includes('diffFiles.length > 0'), 'changed-file panel should be hidden when there are no changed files')
assert.ok(sheetFile.includes('activeSheet === "details"'), 'VCS and file status should be consolidated into the details bottom sheet')
assert.ok(sheetFile.includes('diffFiles.length > 0 ?'), 'details sheet should summarize changed files when diff data exists')
const sidecar = readFileSync(new URL('./hooks/useSessionSidecar.ts', import.meta.url), 'utf8')
assert.ok(sidecar.includes('api.loadProjectCurrent(config, directory)'), 'project dashboard should use /project/current')
assert.ok(sidecar.includes('api.loadVcs(config, directory)'), 'project dashboard should use /vcs')
assert.ok(sidecar.includes('api.loadFileStatus(config, directory)'), 'project dashboard should use /file/status')
assert.ok(/\.project-dashboard[\s\S]*?grid-template-columns:\s*repeat\(3/.test(styles), 'project dashboard should render as compact cards on wide screens')
assert.ok(/@media \(max-width: 780px\)[\s\S]*?\.project-dashboard[\s\S]*?grid-template-columns:\s*1fr/.test(styles), 'project dashboard should stack on mobile')
assert.ok(app.includes('connectionState'), 'sessions view should track connection state separately from one-off runtime errors')
assert.ok(useSessions.includes('backgroundFailureCountRef.current += 1'), 'background refresh should count failures before showing persistent offline errors')
assert.ok(useSessions.includes('backgroundFailureCountRef') && useSessions.includes('current = 0'), 'transient failures should reset counter on success')
assert.ok(sessionList.includes('connection-pending'), 'initial slow connection should show an explicit loading state instead of an empty sessions list')

assert.ok(app.includes('showNewSessionPicker'), 'New Session should open a per-session folder picker instead of applying one global folder')
assert.ok(api.includes('listFiles(config: ServerConfig, path: string, directory?: string)'), 'API should expose OpenCode /file for directory browsing')
const folderPicker = readFileSync(new URL('./components/FolderPicker.tsx', import.meta.url), 'utf8')
const folderPickerHook = readFileSync(new URL('./hooks/useFolderPicker.ts', import.meta.url), 'utf8')
assert.ok(folderPicker.includes("t('sessions.newSessionTitle')"), 'folder picker should be localized')
assert.ok(folderPickerHook.includes('CURSOR_STORAGE_KEY'), 'last new-session folder should persist separately from connection settings')
assert.ok(folderPickerHook.includes('export function dirParent'), 'folder picker should navigate absolute paths up through drive roots')
assert.ok(folderPickerHook.includes('api.loadPath(config)'), 'folder picker should start from the server directory when nothing is saved')
assert.ok(folderPickerHook.includes('api.listFiles(config, "", dir || undefined)'), 'folder picker should list the root of any absolute directory via ?directory=')
assert.ok(folderPicker.includes('onBrowse(item.absolute)'), 'folder picker should jump into folders by their absolute path')
assert.ok(app.includes('api.createSession(config, "Mobile session", activeModel, directory)') || useSessions.includes('api.createSession(config, "Mobile session"'), 'new sessions should pass only the picked directory to OpenCode')
assert.ok(app.includes('isProjectDirectory(pathInfo)') || useSessions.includes('isProjectDirectory(pathInfo)'), 'new session creation should reject folders that OpenCode resolves to the global project')
assert.ok(useSessions.includes('.some((s) => s.id === created.id)'), 'newly created sessions should be inserted before any refresh')
assert.ok(useSessions.includes('const refreshSessions = useCallback'), 'session refresh should accept a newly created session to preserve across stale React state')
assert.ok(api.includes('createSession(config: ServerConfig, title?: string, model?: ModelSelection, directory?: string)'), 'createSession API should accept a directory')
assert.ok(api.includes('withDirectory("/session", directory)'), 'new session creation should append ?directory= when set')
assert.ok(api.includes('loadTodo(config: ServerConfig, sessionID: string, directory?: string)'), 'todo requests should be directory-aware')
assert.ok(api.includes('loadDiff(config: ServerConfig, sessionID: string, directory?: string)'), 'diff requests should be directory-aware')
assert.ok(api.includes('abort(config: ServerConfig, sessionID: string, directory?: string)'), 'abort requests should be directory-aware')
assert.ok(api.includes('listGlobalSessions(config: ServerConfig)'), 'sessions view should use global session discovery when available')
assert.ok(api.includes('x-next-cursor'), 'global session discovery should page through all experimental session results')
assert.ok(useSessions.includes('api.listGlobalSessions(config).catch(() => api.listSessions(config)'), 'sessions loaded via global discovery with fallback')
assert.ok(useSessions.includes('api.loadLatestMessage') === false, 'latest-message N+1 removed for speed')
assert.ok(useSessions.includes('session.time.updated'), 'sessions use time.updated for ordering')

const themeVariant = readFileSync(new URL('./context/themeVariant.tsx', import.meta.url), 'utf8')
assert.ok(themeVariant.includes('localStorage.getItem(STORAGE_KEY)'), 'theme preference should persist separately from server settings')
assert.ok(styles.includes(':root[data-theme="dark"]'), 'dark mode should override design tokens through CSS variables')

const markdownRenderer = readFileSync(new URL('./components/Markdown.tsx', import.meta.url), 'utf8')
assert.ok(markdownRenderer.includes('ReactMarkdown'), 'messages should use a maintained Markdown renderer')
assert.ok(markdownRenderer.includes('remarkGfm'), 'messages should support GitHub-flavored Markdown')
assert.ok(/\.message-content pre[\s\S]*?overflow-x:\s*auto/.test(styles), 'fenced code blocks should render as scrollable blocks')

assert.match(icons, /export const RefreshIcon/, 'RefreshIcon should exist for idle refresh UI')

// Sesiones de acceso rápido con scroll y sin topes artificiales
assert.ok(!sessionList.includes('favoriteSessions.slice(0, 5)'), 'favorites should not be hard-capped at 5')
assert.ok(!sessionList.includes('recentFiltered.slice(0, 5)'), 'recent sessions should not be hard-capped at 5')
assert.ok(styles.includes('.quick-access-list') && styles.includes('overflow-y: auto'), 'quick access list should be scrollable')

// Spinner de 9 cuadrados en vez de la pill "Ocupado" para sesiones corriendo
const quickAccess = readFileSync(new URL('./components/QuickAccessCard.tsx', import.meta.url), 'utf8')
assert.ok(quickAccess.includes('GridSpinner'), 'busy sessions should render the 9-square spinner')
assert.ok(!quickAccess.includes('pill ${session.status}'), 'busy/retry should not share a single pill class')
const gridSpinner = readFileSync(new URL('./components/GridSpinner.tsx', import.meta.url), 'utf8')
assert.ok(gridSpinner.includes('Array.from({ length: 9 })'), 'grid spinner should render 9 squares')
assert.ok(/\.gs-4\s*\{[^}]*animation:\s*none/.test(styles), 'center square of the grid spinner must stay fixed')
assert.ok(/\.gs-1\s*\{[^}]*animation-delay:\s*0\.15s/.test(styles) && /\.gs-6\s*\{[^}]*animation-delay:\s*0\.9s/.test(styles), 'edge squares should pulse in sequence')
assert.ok(/@keyframes gs-pulse[\s\S]*?0%, 100% \{ opacity: 1;/.test(styles), 'gs-pulse should animate the traveling trail')
assert.ok(!styles.includes('pixel-spinner') && !styles.includes('.composer-cost') && !styles.includes('.stream-dot'), 'removed spinners and chat cost label should not reappear')
assert.ok(!styles.includes('image-rendering: pixelated'), 'pixelated image rendering on the spinner should not reappear')
assert.ok(msgList.includes('GridSpinner'), 'session loading state should show the grid spinner')
assert.ok(msgList.includes('aria-hidden="true"'), 'loading text should not duplicate the spinner live region')

// Mensaje optimista: confirmación por reintento + orden estable por time.created
assert.ok(useMessages.includes('optimisticIDsRef'), 'send flow should track optimistic ids in a ref for async confirmation')
assert.ok(useMessages.includes('optimisticTextsRef'), 'send flow should track optimistic texts to recognize the SSE echo')
assert.ok(useMessages.includes('part.type === "text"'), 'SSE echo must be a text part to be matched as a user message')
assert.ok(useMessages.includes('await then().catch'), 'optimistic confirmation should fetch once after POST (TUI-like, sin poll)')
assert.ok(useMessages.includes('merged.sort((a, b) => (a.info.time.created'), 'message merge should sort by time.created so confirmed user messages land in position')

// Touch: hit targets táctiles (WCAG 2.5.8); excepción: composer compacto (36px) por pedido
assert.ok(styles.includes('@media (pointer: coarse), (max-width: 780px)'), 'touch targets should scale up on coarse pointers')
assert.ok(/@media \(pointer: coarse\), \(max-width: 780px\)[\s\S]*?min-width: 44px[\s\S]*?min-height: 44px/.test(styles), 'btn-icon should be at least 44px on touch')
assert.ok(/\.composer-bar-btn\s*\{[^}]*min-height:\s*3[06]px/.test(styles), 'composer send/stop buttons stay compact (30-36px) by explicit request')
assert.equal((styles.match(/\.gs-3\s*\{/g) || []).length, 1, 'grid spinner gs-3 step should be defined exactly once')
assert.ok(/\.composer-input-wrap textarea[\s\S]*?padding: 0\.5rem 2\.5rem 0\.5rem 2\.4rem/.test(styles), 'composer textarea padding should match the inline buttons (no dead 4.4rem)')

// A11y: labels localizados en composer y nav
assert.ok(composer.includes("aria-label={t('composer.inputLabel')}"), 'composer textarea should have a localized aria-label')
assert.ok(composer.includes("title={t('composer.send')}"), 'composer send button should use a localized title')
const navBar = readFileSync(new URL('./components/NavBar.tsx', import.meta.url), 'utf8')
assert.ok(navBar.includes("t('nav.lightMode')") && navBar.includes("t('nav.darkMode')"), 'theme toggle should use localized labels')

// Memo de props del chat: sin objetos literales por render
assert.ok((app + controller + baseChatPropsSource).includes('const baseChatProps') && (app + controller + baseChatPropsSource).includes('useMemo'), 'chat props should be memoized to avoid cascading re-renders')

// Menú de niveles de pensamiento en el toggle del modelo del header
const chatView = readFileSync(new URL('./components/ChatView.tsx', import.meta.url), 'utf8')
const modelUtils = readFileSync(new URL('./utils/model-utils.ts', import.meta.url), 'utf8')
assert.ok(chatView.includes('ThinkingLevels'), 'model toggle should open a menu with thinking levels')
assert.ok(chatView.includes('onChangeVariant'), 'model toggle menu should switch the thinking level directly')
assert.ok(chatView.includes("t('detail.changeModel')"), 'model toggle menu should offer changing the model')
assert.ok(useAI.includes('activeModelVariants'), 'active model variants should come from useAI')
assert.ok(useAI.includes('variantsOf(modelOptions, activeModelOption)'), 'active model variants must be computed over the full model list (recent models included)')
assert.ok(useAI.includes('activeModelOption?.variant'), 'active model variant should derive from the resolved option, not stale state')
assert.ok(!app.includes('variantGroups.groups.get(modelKey(activeModelOption))'), 'active model variants must not come from variantGroups (excludes recent models)')
assert.ok(modelUtils.includes('export function variantsOf') && modelUtils.includes('export function groupModels'), 'model variants should be computed by shared helpers (DRY)')
const settingsPanel = readFileSync(new URL('./components/SettingsPanel.tsx', import.meta.url), 'utf8')
assert.ok(settingsPanel.includes('variantsOf(modelOptions, selected)'), 'settings should reuse the shared variants helper')
const bottomSheet = readFileSync(new URL('./components/BottomSheet.tsx', import.meta.url), 'utf8')
assert.ok(bottomSheet.includes('groupModels(options)'), 'model sheet should reuse the shared grouping helper')
assert.ok(bottomSheet.includes('push(group.base, ...group.variants)'), 'model sheet should render variants so thinking levels can be picked')
assert.ok(styles.includes('.header-model-menu'), 'model toggle menu should have its own styles')

// Botón Reiniciar PC (Extras de Settings) con confirmación
assert.ok(settingsPanel.includes("t('extras.restartHost')") && settingsPanel.includes('RefreshIcon'), 'settings extras should offer a restart action')
assert.ok(settingsPanel.includes('onRestartHost'), 'settings restart should call the host restart handler')
assert.ok((app + hostActions).includes('handleRestartHost') && (app + hostActions).includes("shutdown /r /t 10"), 'host restart should run through the server shell with a delay')
assert.ok((app + hostActions).includes("shutdown /s /t 0"), 'host shutdown should still run through the server shell')

// Envío: una falla de confirmación/refresh NO debe parecer una falla de envío
assert.ok(useMessages.includes('let ok = false'), 'send flow should track whether the POST itself succeeded')
assert.ok(useMessages.includes('ok = true'), 'send flow should mark success only after the POST resolves')
assert.ok(useMessages.includes('if (ok)'), 'confirmation loop should only run after a successful POST')
assert.ok(useMessages.includes('return ok'), 'send flow should return the POST success boolean')
assert.ok(useMessages.includes('removeOptimistic(optimisticMessage.info.id)'), 'optimistic message should be rolled back when the send truly failed')
assert.ok(!chatView.includes('shutdown /r'), 'chat overflow should not duplicate the host restart (it lives in Settings extras)')

// Cola de prompts ELIMINADA por completo: el envío es directo y el server
// gestiona la concurrencia (encolar en la app causaba mensajes perdidos).
const featureFlags = readFileSync(new URL('./hooks/useFeatureFlags.ts', import.meta.url), 'utf8')
assert.ok(!featureFlags.includes('promptQueue'), 'prompt queue should be removed entirely')
assert.ok(!useMessages.includes('queuedPrompts'), 'useMessages should not hold queued prompts')
assert.ok(!useMessages.includes('queuePrompt'), 'useMessages should not expose queuePrompt')
assert.ok(!chatView.includes('queuedPrompts'), 'ChatView should not render a queued prompt badge or panel')

// Modo híbrido v1/v2: el server opencode v2 (beta) usa /api + { data } y el
// v1 rutas raíz. Auto-detección en health + toggle forzado en Settings.
const apiSource = readFileSync(new URL('./api.ts', import.meta.url), 'utf8')
assert.ok(apiSource.includes('resolveApiVersion'), 'API should resolve v1 vs v2 dialect')
assert.ok(apiSource.includes('rememberApiVersion'), 'API should cache the detected version per server')
assert.ok(apiSource.includes('unwrapData'), 'v2 responses wrapped in { data } should be unwrapped')
assert.ok(apiSource.includes('toMessageEnvelopeV1'), 'v2 messages should be mapped to v1 envelopes')
assert.ok(apiSource.includes('toSessionV1'), 'v2 sessions should be mapped to v1 sessions')
const useSSESource = readFileSync(new URL('./hooks/useSSE.ts', import.meta.url), 'utf8')
assert.ok(useSSESource.includes('api/event'), 'SSE on v2 should connect to /api/event (the v2 server exposes it)')
assert.ok(useSSESource.includes('resolveApiVersion'), 'SSE should use sync resolveApiVersion to avoid blocking the connect() on a health probe')
assert.ok(settingsPanel.includes('settings.apiVersion'), 'Settings should expose the API version selector')
assert.ok(useConfig.includes('apiVersion: "auto"'), 'default config should auto-detect API version')

// Polling: en no-full el fetch de mensajes NO se saltea si el SSE está caído
// (túnel móvil) — si no, la respuesta del modelo nunca llega hasta el final.
assert.ok((app + lifecycle).includes('const sseLive = streamState === "streaming"'), 'message fetch skip should require a live SSE stream')
assert.ok((app + lifecycle).includes('!skip)'), 'message fetch should still run when the SSE is down')

console.log('ui regression tests passed')
